FROM node:16-alpine

WORKDIR /usr/src/app #Set the working directory

COPY package*.json ./ # Copy the package.json to install dependencies

RUN npm install

COPY . . # To copy the code

EXPOSE 3000 # Exposing port 3000 to access externally

CMD ["npm", "start"] # Command to run thr app
